In [1]:
# imports
import pandas as pd

from sklearn.linear_model import LinearRegression

from sklearn.metrics import root_mean_squared_error

from sklearn.model_selection import train_test_split

from sklearn.dummy import DummyRegressor

# Practice

In [2]:
# get data from the 'houses_clean.csv'. 
# The CSV file is present in the current folder
df = pd.read_csv('houses_clean.csv')

In [3]:
# sanity check, dataframe check
df.head()

   beds  baths    size  lot_size      price
0     3    2.5  2590.0   6000.00   795000.0
1     4    2.0  2240.0      0.31   915000.0
2     4    3.0  2040.0   3783.00   950000.0
3     4    3.0  3800.0   5175.00  1950000.0
4     2    2.0  1042.0      0.00   950000.0

In [4]:
# Descriptive Stats
df.describe()

              beds        baths          size     lot_size         price
count  2521.000000  2521.000000   2521.000000  2521.000000  2.521000e+03
mean      2.877033     2.171956   1758.998017  3240.947017  9.668217e+05
std       1.247518     1.004397    921.608036  2872.985386  8.870111e+05
min       1.000000     0.500000    250.000000     0.000000  1.590000e+05
25%       2.000000     1.500000   1086.000000     1.000000  6.050000e+05
50%       3.000000     2.000000   1580.000000  3080.000000  8.130000e+05
75%       4.000000     2.500000   2270.000000  5500.000000  1.115000e+06
max      15.000000     9.000000  11010.000000  9998.000000  2.500000e+07

In [5]:
# Check for nulls
df.isna().sum()

beds        0
baths       0
size        0
lot_size    0
price       0
dtype: int64

In [6]:
# set target and features
y = df.price
X = df.drop('price', axis=1)

In [7]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [8]:
# compare sizes
X_train.shape, X_test.shape

((1890, 4), (631, 4))

In [9]:
# instantiate DummyRegressor() model
dum = DummyRegressor()

In [10]:
# fit
dum.fit(X_train, y_train)

DummyRegressor()

In [11]:
# predict and score
dum_preds = dum.predict(X_test)
dum_r2 = dum.score(X_test, y_test)
dum_rmse = root_mean_squared_error(y_test, dum_preds)
print(f'The r^2 is {dum_r2} and the RMSE is {dum_rmse}')

The r^2 is -0.005112125354397756 and the RMSE is 657317.5792720307

# ToDo

In [12]:
# Simple Linear Regression
# Create a feature matric with one feature.
X_single_train = X_train[['size']]

In [15]:
# instantiate and train a linear regression algorithm
slr = LinearRegression()
slr.fit(X_single_train, y_train)

LinearRegression()

In [18]:
# predict and score
slr_preds = slr.predict(X_test[['size']])
slr_r2 = slr.score([['size']], y_test)

/opt/venv/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

ValueError: dtype='numeric' is not compatible with arrays of bytes/strings.Convert your data to numeric values explicitly instead.

In [ ]:
# instantiate and train an MLR algorithm

In [ ]:
# predict and score

In [ ]:
# Recap
print(f'The r^2 is {dum_r2} and the RMSE is {dum_rmse}')
print(f'The r^2 is {slr_r2} and the RMSE is {slr_rmse}')
print(f'The r^2 is {mlr_r2} and the RMSE is {mlr_rmse}')

For any help, refer to the solution notebook present in the current directory.